### ISSUE TITLE
possible clarification of "Debian Packages" page

### ISSUE THREAD

**Issue by RunningLight** [machinekit/machinekit.github.io#23]
The "Debian Packages" page takes the user through the steps to install machinekit on a Beaglebone. In the step labeled "Post-Installation Hints", the entry for Beaglebone says to see Alex's installation hints. The hyperlink provided points to a page titled "Creating a Machinekit Debian Image". This page starts back at the beginning with downloaded a debian image and by step 7 is repeating the installation of machinekit already covered in "Debian Packages". Only steps 4 and 8 on Alex's page seem critical to me in the context of the referral: (step 4) create the user 'machinekit' with certain sudo permissions and (step 8) deal with unneeded capes. There's nothing wrong with Alex's page, it's just that it doesn't (and I don't think it was intended to) fit the flow of "Debian Packages." IMHO the basic information needed to set up machinekit should be self-contained on machinekit.github.io.

As well, since this documentation seems directed toward a new user, wouldn't it be better to have a post-install script in the distro which creates and sets up user 'machinekit'?

**Comment by luminize** [comment]
closing this issue in favour of the availability of the RCN images. If this is incorrect we can open a new issue on https://github.com/machinekit/machinekit-docs/issues
