### ISSUE TITLE
Website needs documentation for *building* Machinekit

### ISSUE THREAD

**Issue by zultron** [machinekit/machinekit.github.io#25]
This was brought up in machinekit/machinekit#341 after I suggested a lot of trouble after a list poster asked about failed build deps and I didn't know the simple `apt-get build-dep machinekit`.

A build doc should also cover args to `./configure`, the `V=1` variable for `make`, and of course `make setuid`.

**Comment by luminize** [comment]
I think the current updated website has ample information on building machinekit. Closing this issue.
