### ISSUE TITLE
'Getting started on Beaglebone' documentation

### ISSUE THREAD

**Issue by zultron** [machinekit/machinekit.github.io#39]
In his wiki, Alex/@strahlex has stashed away a [nice document][1] whose first four steps help get a user with a new Beaglebone from bare metal to running on RCN's images and a shell prompt; from this point, the ['Debian Packages'][2] page picks up to guide her through Machinekit package installation.

It would be great to have parts of this on http://machinekit.io/docs somewhere.  I might well be missing something, but it looks like there's plenty about installing packages, and nothing about getting Debian onto the Beaglebone.  This is unnecessary for x86, since there's an official installer with abundant support resources.  However, because RCN's are 3rd-party images and there are several road-bumps new users repeatedly hit, it seems like there should at least be a pointer to the project's supported images and a few instructions like on Alex's page.  Those plus a little more flesh in step 3 about flashing the bootloader and using the boot button might solve 80% of new user problems we see on the list.

I don't have enough experience using Machinekit on BB to know about the rest of the steps following # 4.  For example, Alex's document and other folks' posts recommend creating a 'machinekit' user, adding it to various groups and giving it sudo privileges.  IIRC the default 'debian' user out of the box is already set up with everything, incl. Xenomai and kmem access, thanks to help from RCN.  IMO, this type of 'getting started' documentation should be trimmed down to bare essentials and standardized as much as possible to make support for the basic configuration more manageable.  (I predict we're going to get slammed now that Michael's Machinetalk and Alex's GUIs are unlocking the power of Machinekit!)

[1]: https://github.com/strahlex/asciidoc-sandbox/wiki/Creating-a-Machinekit-Debian-Image
[2]: http://www.machinekit.io/docs/packages-debian/

**Comment by zultron** [comment]
I'm trying to find where to download the latest Beaglebone images, but can't seem to find the link on machinekit.io.  Anyone can tell me?

Apologies, I'm being deliberately obtuse here, but I really am going to google as the next step in my search.

**Comment by zultron** [comment]
Try number two, found http://beagleboard.org/latest-images, but it seems suspicious that the latest is from May.  Anyway, I'll give it a whirl.

**Comment by zultron** [comment]
Hmm, seems that's the old image with non-upgradeable kernel.  Hopefully third time's the charm:  https://github.com/strahlex/asciidoc-sandbox/wiki/Creating-a-Machinekit-Debian-Image

**Comment by zultron** [comment]
Pasted from the list:

On 01/13/2015 12:33 AM, Bas de Bruijn wrote:
> 
> On 13 Jan 2015, at 07:30, John Morris <john@zultron.com> wrote:
> 
>> If anyone wants to volunteer to write a 'Getting started on
>> Beaglebone' page for the machinekit.io website, I'd be eternally
>> grateful.  There's abundant info here to get started with:
>> 
>> https://github.com/machinekit/machinekit.github.io/issues/39
> 
> Would you want that at the machinekit.io location or just a reference
> to the new machinekit-docs? Let’s work out the documentation matrix
> with different “setting up” tuts.

I don't know, except my gut says that the docs should be kept 'vendor neutral', and of course the machinekit.io site was the first place I thought to look for pointers to prepare the Beaglebone before installing packages.  Others (like yourself) who've actually looked at the docs are more qualified to say than I am.  ;)

**Comment by luminize** [comment]
Well, no real opinion, other than that the question will pop up on the machinekit list from time to time, and I think maintaining on machinekit-docs is easier.

You might get 2 locations people search instead of 1, and it's a good fly catcher to have people searching the real documentation about other subjects like running and using Machinekit.

But my mind isn't set in concrete :)

**Comment by strahlex** [comment]
I started a BeagleBone Black Machinekit beginners guide some time ago. It may be a good starting point for the guide: https://github.com/strahlex/asciidoc-sandbox/wiki/BeagleBone-Black

**Comment by zultron** [comment]
Nice start, @strahlex.

Wish I'd seen @brandonheller's [blog][1] ([posted][2] on the list a while back) last night.  More good material for such a document.

[1]:  https://designmakeshare.wordpress.com/2014/12/29/faster-and-easier-machinekit-install-using-packages/
[2]:  https://groups.google.com/d/msg/machinekit/nFIo1_WTtyQ/ved66v8Ihq8J

**Comment by zultron** [comment]
RCN's Machinekit image link:
    http://elinux.org/Beagleboard:BeagleBoneBlack_Debian#BBW.2FBBB_.28All_Revs.29_Machinekit

Looks like the http://beagleboard.org/latest-images link was updated with the latest images.

**Comment by strahlex** [comment]
Nice, I will try them out.

John Morris writes:

> RCN's Machinekit image link:
>     http://elinux.org/Beagleboard:BeagleBoneBlack_Debian#BBW.2FBBB_.28All_Revs.29_Machinekit
>
> Looks like the http://beagleboard.org/latest-images link was updated with the latest images.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/machinekit/machinekit.github.io/issues/39#issuecomment-77588249

-- 
Alexander Rössler

**Comment by luminize** [comment]
@zultron do the instructions in the machinekit-docs close this issue?
