### ISSUE TITLE
Need to acknowledge new Raspberry Pi 2 Model B

### ISSUE THREAD

**Issue by RunningLight** [machinekit/machinekit.github.io#42]
http://www.machinekit.io/docs/packages-debian/ is somewhat ambiguous now that the Raspberry Pi Foundation has released its new Raspberry Pi 2 Model B, which has an arm7 cpu. Yes, our documentation explicitly says "arm6/Raspberry Pi" but I suspect many noobs will miss the significance of the wording.

Since we don't yet have a Xenomai kernel for the Raspberry Pi 2 Model B, and sidebar conversations suggest it may be a while, I believe this page needs at least a prominent note that it refers to the original Raspberry Pi.

**Comment by mhaberler** [comment]
@kinsamanka can this be close?
