### ISSUE TITLE
docs link broken (!)

### ISSUE THREAD

**Issue by mhaberler** [machinekit/machinekit.github.io#52]
Ahem.

That is embarrassing: "Machinekit Documentation" from http://www.machinekit.io/docs/home/ gets a 404:

 https://github.com/machinekit/machinekit-docs/blob/master/machinekit-documentation/documents-index.asciidoc

**Comment by luminize** [comment]
due to recent work some pages got shifted on the machinekit-docs repo.
will make a PR for that asap
