### ISSUE TITLE
Building from source needs  pkg-config

### ISSUE THREAD

**Issue by sirop** [machinekit/machinekit.github.io#55]
Without
```
 sudo apt-get install pkg-config
```
`./autogen.sh` yields:
```
configure.ac:30: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:92: error: possibly undefined macro: AC_DEFINE
configure.ac:95: error: possibly undefined macro: AC_SUBST
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

My environment:
```
$ uname -a
Linux debian-cml2 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u4 x86_64 GNU/Linux
```

**Comment by mhaberler** [comment]
could you post a PR adding that prerequisite to machinekit/machinekit/debian/<the right file>?

**Comment by sirop** [comment]
This was rather an ad-hoc solution of mine as I did not know that https://github.com/machinekit/machinekit/blob/master/debian/control.in#L6-L20 were not pulled in.
`pkg-config` is also in this file.

So the actual issue is https://github.com/machinekit/machinekit-docs/issues/71 .

And I'll close this one.
