### ISSUE TITLE
correct location to repository after CI and Buildbot work

### ISSUE THREAD

**Issue by luminize** [machinekit/machinekit.github.io#57]
@zultron do the instructions on the website at http://www.machinekit.io/docs/building-from-source/ need to point to `builder2.zultron.com` instead of `deb.dovetail-automata.com` ?

I can update that, but just need to know if that is the correct change.

**Comment by zultron** [comment]
@luminize No, `builder2.zultron.com` was temporary just for testing.  We do need to update the docs, but we haven't decided how yet.  Until then, the current docs are fine as-is.  Thanks!
