### ISSUE TITLE
Search Bar on top of page

### ISSUE THREAD

**Issue by strahlex** [machinekit/machinekit.github.io#60]
I usually expect the search bar on top of the webpage. I think this should also be the case on the Machinekit website.

**Comment by strahlex** [comment]
Some examples:
Github - top left
https://developers.google.com/protocol-buffers/docs/faq - top right
http://docs.getchip.com/chip.html#installing-c-h-i-p-sdk - top left
https://www.python.org/ - top right-ish

Bottom of the page is the last place where I look for a search bar.

**Comment by luminize** [comment]
We should put this issue in machinekit-docs. This entire repo is merged into that one :)
@mhaberler Shall we remove this entire repo? Or keep around for historical purposes?

**Comment by mhaberler** [comment]
@strahlex fine, send a PR

@luminize I am loosing you on "this entire repo"  - what are you proposing?

**Comment by luminize** [comment]
> On 24 Jun 2016, at 23:01, Michael Haberler <notifications@github.com> wrote:
> 
> @strahlex fine, send a PR
> 
> @luminize I am loosing you on "this entire repo" - what are you proposing?
> 
The site is built from machinekit/machinekit-docs, and not from machinekit/machinekit.github.io

**Comment by mhaberler** [comment]
yes, and what you see on www.machinekit.io is served from machinekit/machinekit.github.io which is fed by the website formatting job via git

so deleting machinekit/machinekit.github.io will delete the  www.machinekit.io website

**Comment by luminize** [comment]
> On 24 Jun 2016, at 23:50, Michael Haberler <notifications@github.com> wrote:
> 
> yes, and what you see on www.machinekit.io is served from machinekit/machinekit.github.io which is fed by the website formatting job via git
> 
> so deleting machinekit/machinekit.github.io will delete the www.machinekit.io website
> 
Fair enough, my misunderstanding. How should we "prevent" the making of pr etc?

**Comment by ArcEye** [comment]
PR #179 fixes

![selection_015](https://cloud.githubusercontent.com/assets/770392/16356512/0d016ccc-3ad2-11e6-939f-63be8e83f059.png)

![selection_016](https://cloud.githubusercontent.com/assets/770392/16356513/1232a0b2-3ad2-11e6-97d2-5cebdf442387.png)

**Comment by mhaberler** [comment]
@luminize I made the one-line description sufficiently repelling ;)

**Comment by luminize** [comment]
> On 25 Jun 2016, at 16:14, Michael Haberler <notifications@github.com> wrote:
> 
> @luminize I made the one-line description sufficiently repelling ;)

Yes indeed! I'll run thru the issues and clean them up or take them over to machinekit-docs, after that I'll disable the tracker
