### ISSUE TITLE
Flatter structure?

### ISSUE THREAD

**Issue by strahlex** [machinekit/machinekit.github.io#61]
In my opinion the Machinekit website has to many sub-pages (e.g. http://www.machinekit.io/community/home/) I need to click 2 times to get the relevant information -> the link to the Google Groups page. Most websites these days have a flat structure without many sub-pages. Just to reference a few:
https://developers.google.com/protocol-buffers/docs/faq
http://docs.getchip.com/chip.html#installing-c-h-i-p-sdk
https://facebook.github.io/react/support.html

This design makes it possible to use the browser search to find the information + works a lot better on phones and tablets.

**Comment by koppi** [comment]
It gets more and more complicated. – A plain text README.txt would probably be enough. I do not like this machinekit sub-project. It sucks too much time and energy from the core developers. Now we have to think about html jekyll plugins, css and other cruft. What a big waste of time and energy.

**Comment by ArcEye** [comment]
Look forward to your PR

**Comment by luminize** [comment]
closing because issue has been brought to https://github.com/machinekit/machinekit-docs/issues
